### PR TITLE
added typings.d.ts

### PR DESCRIPTION
**Pull request by CzBuCHi**
added simple d.ts file for typescript

### CODE REVIEW

**Comment by 75lb** [comment]
hi, thanks for the contribution but this patch does not belong in the core module. Thanks anyway, and let me know if you find anything else.

**Comment by CzBuCHi** [comment]
no idea what u mean by 'core module' :( ... typings are created based on sources ..

**Comment by 75lb** [comment]
by 'core module' I mean *this* module.. this is a Javascript module, not Typescript, Coffeescript, Dart or any other higher-order, compile-to-javascript language.. Not all users of this module use Typescript, including me.

In cases like this it's best to create an additional module extending this one, e.g. `command-line-commands-ts` or similar. It's  a better idea - publish a specialist module maintained by a Typescript developer for use by other Typescript developers. Hope that makes sense.

**Comment by CzBuCHi** [comment]
ah .. i understand now .... but that precisely why d.ts files exists - for ex. moment.js is js library but has its own moment.d.ts for typescript consumers (they got compiler errors if used wrongly) - js consumer simply ignores d.ts all tohether ...

but i understand, that u dont wanna update d.ts if any change in api occurs ...

**Comment by 75lb** [comment]
moment is a monolithic library - it solves dozens, maybe hundreds of date-related problems.. this is a "do a single job" module..

**Pull request closed without merging**
