### PR TITLE
Feature: handle unknown command

### PR DESCRIPTION
**Pull request by lipsumar**
Having command-line-commands return the command it doesn't understand makes it cleaner for to show what went wrong.

### CODE REVIEW

**Comment by 75lb** [comment]
Thanks bro, will look at this today.

**Comment by 75lb** [comment]
FYI, i have merged this and am continuing to work on a new release.. will let you know once it is ready.

**Comment by 75lb** [comment]
v1.0.0 is done.. in the end, i changed the API to simplify and reduce the scope of the module.. thanks for your input.. let me know if the docs are unclear or if there are any more issues.. cheers!

**Comment by lipsumar** [comment]
Looks good 👍

**Pull request closed without merging**
